# Generated by Django 3.1.3 on 2022-11-05 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_question_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='Choice text', max_length=320),
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.lesson'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='Question text', max_length=320),
        ),
        migrations.AddField(
            model_name='submission',
            name='enrollment_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.enrollment'),
        ),
    ]
